# -*- coding: utf-8 -*-
"""modelsv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWM2eU4k31vSD-Zq2Rw_um3LQqRMeVe-
"""

import warnings, os, pickle
warnings.filterwarnings("ignore")

import torch
import torch.nn as nn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import (
    AutoTokenizer,
    AutoModel,
    AutoModelForCausalLM,
    logging as hf_logging,
)
from torch.utils.data import Dataset, DataLoader

hf_logging.set_verbosity_error()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


from collections import Counter
from datetime import datetime, timedelta


EMO_MODEL_NAME = "xlm-roberta-base"
LLM_MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"

NEGATIVE = [
    "angry","furious","annoyed",
    "sad","lonely","devastated","disappointed",
    "afraid","terrified","anxious","apprehensive",
    "guilty","ashamed","embarrassed",
    "jealous","disgusted"
]
NEUTRAL = [
    "prepared","anticipating","surprised",
    "nostalgic","sentimental","faithful"
]
POSITIVE = [
    "joyful","grateful","confident",
    "caring","content","hopeful",
    "proud","excited","impressed",
    "trusting"
]

EMOTION_SCORE = {
    # VERY NEGATIVE
    "devastated": -3,
    "terrified": -3,
    "ashamed": -3,

    # NEGATIVE
    "sad": -2,
    "lonely": -2,
    "anxious": -2,
    "afraid": -2,
    "guilty": -2,
    "disappointed": -2,

    # MILD NEGATIVE
    "annoyed": -1,
    "apprehensive": -1,
    "jealous": -1,
    "disgusted": -1,

    # NEUTRAL
    "prepared": 0,
    "anticipating": 0,
    "surprised": 0,
    "nostalgic": 0,
    "sentimental": 0,
    "faithful": 0,

    # POSITIVE
    "content": 1,
    "hopeful": 1,
    "trusting": 1,
    "caring": 1,

    # VERY POSITIVE
    "joyful": 2,
    "grateful": 2,
    "confident": 2,
    "proud": 2,
    "excited": 2,
    "impressed": 2,
}



def build_label_maps(split):

    emotions = sorted(set(split["emotion"]))

    emotion2id = {e: i for i, e in enumerate(emotions)}
    id2emotion = {i: e for e, i in emotion2id.items()}

    behaviors = sorted(set(split["behavior"]))

    behavior2id = {b: i for i, b in enumerate(behaviors)}
    id2behavior = {i: b for b, i in behavior2id.items()}

    return (
        emotion2id,
        id2emotion,
        behavior2id,
        id2behavior,
        len(emotion2id),
        len(behavior2id),
    )

class EmotionDataset(Dataset):

    def __init__(
        self,
        hf_split,
        tokenizer,
        emotion2id,
        behavior2id,
        max_len=256
    ):
        self.data = hf_split
        self.tokenizer = tokenizer
        self.emotion2id = emotion2id
        self.behavior2id = behavior2id
        self.max_len = max_len

    def __len__(self):
        return len(self.data)

    def build_text(self, row):

        situation = row["situation"]
        history = row["chat_history"]

        if isinstance(history, list):
            history = " ".join(history)

        return f"Situation: {situation}\nDialogue: {history}"

    def __getitem__(self, idx):
        row = self.data[idx]
        text = self.build_text(row)
        enc = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )

        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),

            "emotion": torch.tensor(
                self.emotion2id[row["emotion"]],
                dtype=torch.long
            ),

            "behavior": torch.tensor(
                self.behavior2id[row["behavior"]],
                dtype=torch.long
            ),
        }

class EmotionModel(nn.Module):

    def __init__(self, n_emo, n_behavior=None, base_model=EMO_MODEL_NAME):

        super().__init__()

        self.encoder = AutoModel.from_pretrained(base_model)
        h = self.encoder.config.hidden_size

        self.emotion_head = self._head(h, n_emo)

        self.behavior_head = (
            self._head(h, n_behavior)
            if n_behavior is not None else None
        )

    @staticmethod
    def _head(hidden, n_out):
        return nn.Sequential(
            nn.Linear(hidden, 256),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(256, n_out),
        )

    def forward(self, input_ids, attention_mask):

        out = self.encoder(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        cls = out.last_hidden_state[:, 0]

        logits = {
            "emotion": self.emotion_head(cls)
        }

        if self.behavior_head is not None:
            logits["behavior"] = self.behavior_head(cls)

        return logits
    @torch.no_grad()
    def predict(self, text: str, tokenizer, id2emotion, id2behavior=None) -> dict:
        self.eval()
        
        device = next(self.parameters()).device 

        batch = tokenizer(
            text, truncation=True, padding=True,
            max_length=128, return_tensors="pt",
        )

        # toàn bộ batch lên cùng device với model
        batch = {k: v.to(device) for k, v in batch.items()}
        logits = self(batch["input_ids"], batch["attention_mask"])
        
        emotion_id = logits["emotion"].argmax(-1).item()
        result = {"emotion": id2emotion[emotion_id]} 
        
        if "behavior" in logits and id2behavior:
            behavior_id = logits["behavior"].argmax(-1).item()
            result["behavior"] = id2behavior[behavior_id]
            
        return result
    



class EmotionMemory:
    def __init__(self):
        self.logs = []

    def add(self, emotion, text):
        self.logs.append({
            "time": datetime.now(),
            "emotion": emotion,
            "text": text
        })

    def get_all(self):
        return self.logs


#Theo dõi điểm cảm xúc theo thời gian, phát hiện xu hướng cải thiện / suy giảm, tính streak tích cực
class MoodTracker:
    """
    Theo dõi lịch sử cảm xúc, tính toán:
    - Mood score timeline (dựa trên EMOTION_SCORE)
    - Rolling average (cửa sổ N bước)
    - Positive streak (số lần liên tiếp cảm xúc tích cực)
    - Trend detection (đang cải thiện / ổn định / suy giảm)
    """

    TREND_WINDOW = 5          
    ROLLING_WINDOW = 3        

    def __init__(self):
        self.memory: list[dict] = []  # {"time": datetime, "emotion": str, "score": int, "text": str}


    def log(self, emotion: str, text: str = ""):
        score = EMOTION_SCORE.get(emotion, 0)
        self.memory.append({
            "time":    datetime.now(),
            "emotion": emotion,
            "score":   score,
            "text":    text,
        })

    def scores(self) -> list[int]:
        return [e["score"] for e in self.memory]

    def rolling_avg(self, window: int | None = None) -> list[float]:
        w = window or self.ROLLING_WINDOW
        s = self.scores()
        return [round(sum(s[max(0, i-w+1):i+1]) / min(i+1, w), 2) for i in range(len(s))]


    def current_trend(self) -> str:
        """'improving' | 'stable' | 'declining'"""
        s = self.scores()
        if len(s) < 2:
            return "stable"
        window = s[-self.TREND_WINDOW:]
        slope = (window[-1] - window[0]) / max(len(window) - 1, 1)
        if slope > 0.3:  return "improving "
        if slope < -0.3: return "declining"
        return "stable "

    def positive_streak(self) -> int:
        streak = 0
        for entry in reversed(self.memory):
            if entry["score"] > 0:
                streak += 1
            else:
                break
        return streak

    def best_emotion(self) -> str | None:
        if not self.memory:
            return None
        return max(self.memory, key=lambda e: e["score"])["emotion"]

    def worst_emotion(self) -> str | None:
        if not self.memory:
            return None
        return min(self.memory, key=lambda e: e["score"])["emotion"]


    def summary_stats(self) -> dict:
        s = self.scores()
        if not s:
            return {}
        return {
            "total_logs":      len(s),
            "avg_score":       round(sum(s) / len(s), 2),
            "best_emotion":    self.best_emotion(),
            "worst_emotion":   self.worst_emotion(),
            "trend":           self.current_trend(),
            "positive_streak": self.positive_streak(),
            "positive_pct":    round(100 * sum(1 for x in s if x > 0) / len(s), 1),
            "negative_pct":    round(100 * sum(1 for x in s if x < 0) / len(s), 1),
        }

# Tóm tắt cảm xúc theo tuần
class WeeklySummary:
    """
    Sinh báo cáo cảm xúc theo tuần từ MoodTracker.
    - Bar chart: tần suất từng cảm xúc
    - Pie chart: phân bố Positive / Neutral / Negative
    - Bảng thống kê văn bản (Markdown-friendly)
    """

    def __init__(self, mood_tracker: MoodTracker):
        self.tracker = mood_tracker

    def _filter_week(self, week_offset: int = 0) -> list[dict]:
        """week_offset=0 → tuần hiện tại, -1 → tuần trước."""
        today = datetime.now().date()
        start = today - timedelta(days=today.weekday()) + timedelta(weeks=week_offset)
        end   = start + timedelta(days=6)
        return [
            e for e in self.tracker.memory
            if start <= e["time"].date() <= end
        ]

    def text_report(self, week_offset: int = 0) -> str:
        entries = self._filter_week(week_offset)
        if not entries:
            return "Không có dữ liệu cho tuần này."

        counts = Counter(e["emotion"] for e in entries)
        scores = [e["score"] for e in entries]
        pos = sum(1 for s in scores if s > 0)
        neu = sum(1 for s in scores if s == 0)
        neg = sum(1 for s in scores if s < 0)
        avg = round(sum(scores) / len(scores), 2)

        today = datetime.now().date()
        start = today - timedelta(days=today.weekday()) + timedelta(weeks=week_offset)
        end   = start + timedelta(days=6)

        lines = [
            f"## Weekly Emotional Summary ({start} → {end})",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Tổng lần log | {len(entries)} |",
            f"| Điểm TB | {avg} |",
            f"| Tích cực | {pos} ({round(100*pos/len(entries))}%) |",
            f"| Trung tính | {neu} ({round(100*neu/len(entries))}%) |",
            f"| Tiêu cực | {neg} ({round(100*neg/len(entries))}%) |",
            f"| Cảm xúc phổ biến nhất | {counts.most_common(1)[0][0]} ({counts.most_common(1)[0][1]} lần) |",
            f"",
            f"### Cảm xúc trong tuần",
        ]
        for emo, cnt in counts.most_common(5):
            bar = "█" * cnt
            lines.append(f"- **{emo}**: {bar} {cnt}")

        return "\n".join(lines)

class Retriever:
    def __init__(self):
        self.vectorizer = TfidfVectorizer(
            ngram_range=(1, 2),
            max_features=50_000,
            sublinear_tf=True,
        )
        self.matrix = None
        self.docs: list[str] = []

    def ingest(self, texts: list[str]):
        self.docs   = texts
        self.matrix = self.vectorizer.fit_transform(texts)
        print(f"Ingested {len(texts)} docs, vocab={len(self.vectorizer.vocabulary_)}")

    def search(self, query: str, k: int = 5) -> list[str]:
        if not query.strip() or self.matrix is None:
            return []
        q_vec = self.vectorizer.transform([query])
        scores = cosine_similarity(q_vec, self.matrix)[0]
        top_k  = scores.argsort()[::-1][:k]
        return [self.docs[i] for i in top_k if scores[i] > 0]

    def save(self, path: str):
        os.makedirs(path, exist_ok=True)
        with open(f"{path}/retriever.pkl", "wb") as f:
            pickle.dump({"vectorizer": self.vectorizer,
                         "matrix": self.matrix,
                         "docs": self.docs}, f)

    @classmethod
    def load(cls, path: str) -> "Retriever":
        with open(f"{path}/retriever.pkl", "rb") as f:
            d = pickle.load(f)
        r = cls()
        r.vectorizer = d["vectorizer"]
        r.matrix     = d["matrix"]
        r.docs       = d["docs"]
        print(f"Loaded retriever: {len(r.docs)} docs")
        return r

class PromptBuilder:
    # Đồng bộ hóa với tất cả nhãn trong EMOTION_SCORE
    EMOTION_GUIDANCE = {
        # VERY NEGATIVE (-3)
        "devastated": "Bạn đang cảm thấy sụp đổ hoàn toàn. Mình ở đây bên bạn.",
        "terrified": "Bạn đang vô cùng sợ hãi. Hãy tìm một nơi an toàn, mình nghe bạn.",
        "ashamed": "Bạn đang cảm thấy hổ thẹn. Đừng quá khắt khe với bản thân, mình không phán xét đâu.",
        
        # NEGATIVE (-2)
        "sad": "Bạn đang thấy buồn. Mình luôn sẵn lòng lắng nghe tâm sự của bạn.",
        "lonely": "Cảm giác cô đơn thật khó khăn. Mình đang ở đây trò chuyện cùng bạn.",
        "anxious": "Bạn đang lo lắng bồn chồn. Hãy thử hít thở sâu một chút nhé.",
        "afraid": "Bạn cảm thấy sợ hãi. Có mình ở đây cùng bạn rồi.",
        "guilty": "Bạn đang thấy tội lỗi. Ai cũng có lúc sai lầm, đừng dằn vặt quá nhé.",
        "disappointed": "Bạn đang thất vọng. Mọi chuyện không như ý thật sự rất buồn.",
        
        # MILD NEGATIVE (-1)
        "annoyed": "Bạn đang thấy hơi bực mình. Nói cho mình nghe chuyện gì làm bạn khó chịu vậy?",
        "apprehensive": "Bạn đang thấy e ngại và lo âu nhẹ.",
        "jealous": "Bạn đang cảm thấy đố kỵ. Đó là cảm xúc con người bình thường thôi.",
        "disgusted": "Bạn cảm thấy ghê tởm hoặc bất bình về điều gì đó.",
        
        # NEUTRAL (0)
        "prepared": "Bạn đã sẵn sàng cho mọi thứ.",
        "anticipating": "Bạn đang chờ đợi một điều gì đó sắp tới.",
        "surprised": "Bạn thấy ngạc nhiên quá đúng không?",
        "nostalgic": "Bạn đang hoài niệm về những kỷ niệm cũ.",
        "sentimental": "Bạn đang sống trong những cảm xúc dạt dào.",
        "faithful": "Bạn đang có niềm tin rất lớn.",
        
        # POSITIVE (1)
        "content": "Bạn đang thấy hài lòng và bình yên. Thật tốt quá.",
        "hopeful": "Bạn đang tràn đầy hy vọng. Hãy giữ vững niềm tin đó nhé.",
        "trusting": "Bạn cảm thấy tin tưởng. Cảm ơn bạn đã tin tưởng chia sẻ với mình.",
        "caring": "Bạn đang dành sự quan tâm cho người khác. Bạn thật tử tế.",
        
        # VERY POSITIVE (2)
        "joyful": "Bạn đang rất vui vẻ! Niềm vui của bạn làm mình cũng vui lây.",
        "grateful": "Bạn đang cảm thấy biết ơn. Trân trọng những điều tốt đẹp thật tuyệt vời.",
        "confident": "Bạn đang rất tự tin. Hãy cứ phát huy thế mạnh của mình nhé.",
        "proud": "Bạn đang tự hào về bản thân. Bạn xứng đáng với điều đó!",
        "excited": "Bạn đang hào hứng quá! Kể cho mình nghe chuyện gì vui thế?",
        "impressed": "Bạn thấy ấn tượng sâu sắc về điều gì đó đúng không?",
    }

    CRISIS_KEYWORDS = ["tự tử", "muốn chết", "không muốn sống", "kill myself", "suicide", "kết thúc cuộc đời", "biến mất mãi mãi", "chấm dứt cuộc sống", "đau khổ quá", "không chịu nổi nữa", "hết cách rồi"]

    def _is_crisis(self, text: str) -> bool:
        t = text.lower()
        return any(k in t for k in self.CRISIS_KEYWORDS)

    def _guidance(self, emotion: str) -> str:
        emotion = emotion.lower()
        return self.EMOTION_GUIDANCE.get(emotion, "")

    def build(self, user_text: str, emotion: str, docs: list[str], history: list[dict] | None = None) -> str:
        guidance = self._guidance(emotion)

        # Context từ RAG
        context_lines = [f"- {d[:120]}" for d in docs[:2] if d.strip()]
        context = "\n".join(context_lines) if context_lines else ""

        # History
        hist_lines = []
        if history:
            for h in history[-6:]:
                role = "Bạn" if h["role"] == "user" else "Mình"
                hist_lines.append(f"{role}: {h['content']}")
        hist_text = "\n".join(hist_lines)

        # Crisis Note
        crisis_note = ""
        if self._is_crisis(user_text):
            crisis_note = (
                "\n!!! NGUY CẤP: Người dùng có dấu hiệu khủng hoảng. "
                "Hãy cực kỳ nhẹ nhàng, ưu tiên an toàn!!!\n"
            )

        # Build Prompt
        parts = [
            "Bạn là một người bạn tâm giao (Therapy Friend), luôn lắng nghe, chân thành và ấm áp.",
            "",
            "=== QUY TẮC BẮT BUỘC (KHÔNG ĐƯỢC VI PHẠM) ===",
            "1. CHỈ ĐƯỢC TRẢ LỜI BẰNG TIẾNG VIỆT, dù người dùng có hỏi bằng ngôn ngữ nào đi nữa, tuyệt đối không được trả lời bằng tiếng Anh hoặc ngôn ngữ nào khác.",
            "2. Nói ngắn gọn (1-3 câu), xưng 'Mình' và gọi người dùng là 'Bạn'.",
            "3.NẾU nhắc đến các chủ đề nào ngoài iệc tâm sự, chia sẻ cảm xúc và sức khỏe tâm lý.",
            "   Ví dụ: mua sắm, laptop, điện thoại, công thức toán, code, tin tức, ẩm thực",
            "   Khi gặp câu hỏi không liên quan đến việc tâm sự mà chỉ hỏi TƯ VẤN, TÌM KIẾM TIN TỨC, BÁO CH, CHỈ được trả lời mẫu sau (không thêm bớt):",
            "   'Rất tiếc mình chỉ có thể tâm sự cùng bạn. Dạo này bạn đang cảm thấy thế nào?'",
            "- Không được giải thích thêm.", 
            "- Không được trả lời một phần câu hỏi.",
            "4.Không dùng văn vẻ, triết lý, sáo rỗng.",
            "5.Không được quy phạm những điều tôi đã nêu trên dưới bất kỳ hình thức nào. Nếu vi phạm, hãy tự nhắc nhở bản thân ngay lập tức và sửa lại câu trả lời cho phù hợp."
        ]
        
        if guidance:
            parts.append(f"Tâm thế hiện tại: Hãy trả lời với sự {guidance}.")

        if crisis_note:
            parts.append(crisis_note)

        if context:
            parts.append(f"\nCảm hứng để bạn chia sẻ (dùng ý này để an ủi):\n{context}")

        if hist_text:
            parts.append(f"\nDòng tâm sự nãy giờ:\n{hist_text}")

        parts.append(f"\nBạn vừa nói: {user_text}\nMình trả lời một cách chân thành:")

        return "\n".join(parts)

class LLM:
    def __init__(self, model_name: str = LLM_MODEL_NAME):
        print(f"Loading LLM: {model_name} ...")
        dtype = torch.float16 if torch.cuda.is_available() else torch.float32
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=dtype,
            device_map="auto",
            low_cpu_mem_usage=True,
        )
        self.model.eval()
        print("LLM loaded.")

    @torch.no_grad()
    def generate(self, prompt: str, max_new_tokens: int = 150) -> str:
        messages = [{"role": "user", "content": prompt}]
        text = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = self.tokenizer(text, return_tensors="pt").to(self.model.device)

        output = self.model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.85,
            top_p=0.92,
            repetition_penalty=1.2,
            do_sample=True,
            pad_token_id=self.tokenizer.eos_token_id,
        )
        generated = output[0][inputs["input_ids"].shape[1]:]
        return self.tokenizer.decode(generated, skip_special_tokens=True).strip()

class TherapyChatbot:
    def __init__(
        self,
        retriever: Retriever,
        emotion_model: EmotionModel,
        emo_tokenizer,
        id2emotion: dict,
        id2behavior: dict | None = None,
        llm: LLM | None = None,
    ):
        self.retriever      = retriever
        self.emotion_model  = emotion_model.to(device).eval()
        self.emo_tokenizer  = emo_tokenizer
        self.id2emotion     = id2emotion
        self.id2behavior    = id2behavior
        self.llm            = llm or LLM()
        self.prompt_builder = PromptBuilder()
        self.chat_history: list[dict] = []
        self.mood_tracker = MoodTracker()                  
        self._emotion_history: list[str] = [] 

    def chat(self, user_input: str, verbose: bool = False) -> str:
        # hân tích cảm xúc
        analysis = self.emotion_model.predict(
            user_input, self.emo_tokenizer,
            self.id2emotion, self.id2behavior,
        )
        emotion = analysis["emotion"]
        self.mood_tracker.log(emotion, text=user_input)
        self._emotion_history.append(emotion)
        
        if verbose:
            print(f"[Analysis] {analysis}")

        # Retrieve context
        docs = self.retriever.search(user_input, k=5)
        if verbose:
            print(f"[RAG] {len(docs)} docs retrieved")

        # Build prompt
        prompt = self.prompt_builder.build(
            user_text=user_input,
            emotion=emotion,
            docs=docs,
            history=self.chat_history,
        )

        # Generate
        response = self.llm.generate(prompt)
        if verbose:
            print(f"[Response] {response}")

        # Update history (giới hạn 10 turns)
        self.chat_history.append({"role": "user",      "content": user_input})
        self.chat_history.append({"role": "assistant", "content": response})
        self.chat_history = self.chat_history[-10:]

        return response


    def reset(self):
        self.chat_history = []
    def save(self, base_path: str = "./chatbot_saved"):
        os.makedirs(base_path, exist_ok=True)
        torch.save(self.emotion_model.state_dict(), f"{base_path}/emotion_model.pt")
        self.emo_tokenizer.save_pretrained(f"{base_path}/emo_tokenizer")
        self.retriever.save(base_path)
        # Save label maps
        with open(f"{base_path}/label_maps.pkl", "wb") as f:
            pickle.dump({"id2emotion": self.id2emotion,
                         "id2behavior": self.id2behavior}, f)
        print(f"Saved to {base_path}/")

    @classmethod
    def from_saved(cls, base_path: str = "./chatbot_saved",
                   n_emo: int = 32, n_behavior: int = 8) -> "TherapyChatbot":
        with open(f"{base_path}/label_maps.pkl", "rb") as f:
            maps = pickle.load(f)

        emo_tok = AutoTokenizer.from_pretrained(f"{base_path}/emo_tokenizer")
        emo_model = EmotionModel(n_emo=n_emo, n_behavior=n_behavior)
        emo_model.load_state_dict(
            torch.load(f"{base_path}/emotion_model.pt", map_location=device)
        )
        retriever = Retriever.load(base_path)
        return cls(
            retriever=retriever,
            emotion_model=emo_model,
            emo_tokenizer=emo_tok,
            id2emotion=maps["id2emotion"],
            id2behavior=maps["id2behavior"],
        )


#Hôm nay mình rất vui vì được điểm cao trong kỳ thi vừa rồi
#Mình thực sự khó chịu vì thái độ của người đó, thật không thể chấp nhận được!
#Mình đang rất lo lắng và sợ hãi về kết quả bài thực tập sắp tới